createdb:
	docker exec -it alpine-postgres12 createdb --username=root --owner=root bankdb
dropdb:
	docker exec -it alpine-postgres12 dropdb --username=root --owner=root bankdb
postgres:
	docker run --name alpine-postgres12 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=secret -p 5432:5432 -d postgres:12-alpine
migrateup:
	migrate -path db/migration -database "postgresql://root:secret@localhost:5432/bankdb?sslmode=disable" -verbose up
migratedown:
	migrate -path db/migration -database "postgresql://root:secret@localhost:5432/bankdb?sslmode=disable" -verbose down
sqlc: 
	docker run --rm -v "%cd%:/src" -w /src kjconroy/sqlc generate

.PHONY: createdb dropdb postgres migrateup migratedown sqlc